[workspace]
members = [
    "crates/phantom-vt",
    "crates/phantom-pty",
    "crates/phantom-git",
    "crates/phantom-app",
]
resolver = "2"

[workspace.package]
edition = "2021"
version = "0.1.0"
