[package]
name = "phantom-pty"
version = "0.1.0"
edition = "2021"

[dependencies]
portable-pty = "0.9.0"
phantom-vt = { path = "../phantom-vt" }
tokio = { version = "1", features = ["rt", "sync", "time", "macros"] }
log = "0.4"
